/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2022

fun main() {
    val input = readFile("/day1")
    val rawGroups = input.readText().split("\n\n")
    val topThree = rawGroups.map { group ->
        group.trim().split("\n").map { it.toInt() }.sum()
    }.sortedDescending().take(3).sum()
    println("max $topThree")
}
