/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2022

import java.lang.IllegalStateException

fun main() {
    val strategyMap = mapOf(
        "A" to 1,
        "B" to 2,
        "C" to 3,
        "X" to 1,
        "Y" to 2,
        "Z" to 3
    )

    val lines = readFile("/day2").readLines()
    val sum = lines.sumOf {
        val splittedLine = it.split(" ")
        getRoundScore(strategyMap.get(splittedLine[0])!!, strategyMap.get(splittedLine[1])!!)
    }
    println("sum $sum")
}

fun getRoundScore(opponent: Int, you: Int): Int {
    // 1 rock, 2 paper, 3 scissor
    // 2-1

    return you + when (you - opponent) {
        1, -2 -> 6
        -1, 2 -> 0
        0 -> 3
        else -> throw IllegalStateException()
    }
}
