/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2022


fun main() {
    val lines = readFile("/day3").readLines()
    // A is 65
    // a is 97
    val sum = lines.sumOf { line ->
        val stringChunks = line.chunked(line.length / 2)
        for(char in stringChunks[0]) {
            if(char in stringChunks[1]) {
                return@sumOf char.code - if(char.isUpperCase()) 38 else 96
            }
        }
        0
    }
    println("sum is $sum")

}
