/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2022


fun main() {
    val lines = readFile("/day4").readLines()

    // example input 20-45,13-44
    val overlappingPairs = lines.filter { input ->
        // this deconstruct is in honor of widar
        val (first, second) = input.split(",")
        val (lowerRangeFirst, upperRangeFirst) = first.split("-").map { it.toInt() }
        val (lowerRangeSecond, upperRangeSecond) = second.split("-").map { it.toInt() }
        val firstRange = lowerRangeFirst..upperRangeFirst
        val secondRange = lowerRangeSecond..upperRangeSecond

        (lowerRangeSecond in firstRange || upperRangeSecond in firstRange) ||
            (lowerRangeFirst in secondRange || upperRangeFirst in secondRange)

    }

    println("overlapping ${overlappingPairs.size}")
}
